	#base "../#customization/scripts/transparent.res"
	#base "../#customization/scripts/damageindicator.res"
	#base "../../ui_overrides/resource/ui/hitmarkers.res"
	#base "../#new/hudlayout.res"
	#base "../#customization/!addons/#enabled/tf2_def_hud/hudlayout.res"